import { FEATURE_KEYS, type FeatureKey } from './features'

const K = FEATURE_KEYS

const FREE: FeatureKey[] = [K.MARKETING_SITE, K.BLOG, K.STORIES]

const STARTER: FeatureKey[] = [
  ...FREE,
  K.TRAINING_MODULES, K.VIDEO_UPLOAD,
  K.DOCUMENT_STORAGE, K.DIRECT_MESSAGES,
]

const PROFESSIONAL: FeatureKey[] = [
  ...STARTER,
  K.MEDICAL_REVIEW_WORKFLOW, K.CAREGIVER_ASSESSMENTS,
  K.SHIFT_MANAGEMENT, K.CHECK_IN_OUT, K.GEOFENCING, K.TIMESHEET_EXPORT,
  K.GROUP_CHANNELS, K.THREADED_REPLIES,
  K.DOCUMENT_VERSIONING, K.DOCUMENT_EXPIRATION_ALERTS,
  K.AI_CARE_ASSISTANT, K.ACTION_LOGGING, K.ESCALATION_DETECTION,
]

const ENTERPRISE: FeatureKey[] = Object.values(FEATURE_KEYS)

export const PLAN_PRESETS: Record<string, FeatureKey[]> = {
  free: FREE,
  starter: STARTER,
  professional: PROFESSIONAL,
  enterprise: ENTERPRISE,
}
